export const INITIAL_DOCS = [
  {
    id: 1,
    category: 'utility',
    icon: 'bolt',
    title:       { en: 'Electricity Shutoff Notice', es: 'Corte de electricidad' },
    issuer:      'Pacific Gas & Electric',
    urgency:     'act-now',
    deadlineLabel: { en: 'Action before May 14', es: 'Acción antes del 14 mayo' },
    daysLeft:    5,
    receivedDate:{ en: 'May 8, 2026',        es: '8 de mayo de 2026' },
    done: false,
    summary: {
      en: 'PG&E says your electricity could be shut off in 5 days. You have an unpaid balance of $342 due May 14. If you don\'t pay or make a plan before that date, your power will be turned off.',
      es: 'PG&E dice que su electricidad podría ser cortada en 5 días. Tiene un saldo pendiente de $342 que vence el 14 de mayo. Si no paga o hace un plan antes de esa fecha, su servicio será cortado.',
    },
    steps: [
      {
        id: 1, done: false,
        title:  { en: 'Call PG&E today',         es: 'Llame a PG&E hoy' },
        detail: { en: 'Ask about the REACH program or Energy Assistance Fund. You may qualify to have your bill reduced or forgiven.', es: 'Pregunte por el programa REACH o Energy Assistance Fund. Puede calificar para reducir o perdonar su deuda.' },
        phone: '1-800-743-5000',
      },
      {
        id: 2, done: false,
        title:  { en: 'Request a payment plan',   es: 'Pida un plan de pago' },
        detail: { en: 'By law PG&E must offer you a plan before shutting off service. Ask for a "deferred payment agreement."', es: 'Por ley, PG&E debe ofrecerle un plan antes de cortar el servicio. Pida un "acuerdo de pago diferido."' },
        phone: null,
      },
      {
        id: 3, done: false,
        title:  { en: 'Make a $50 partial payment', es: 'Haga un pago parcial de $50' },
        detail: { en: 'Paying at least $50 online at pge.com usually delays the shutoff while your request is reviewed.', es: 'Pagar al menos $50 en pge.com generalmente retrasa el corte mientras revisan su solicitud.' },
        phone: null,
      },
    ],
    hiddenPaths: [
      { en: 'If someone in your home has a serious illness, PG&E must give 15 extra days notice before shutoff — mention this when you call.', es: 'Si alguien en su hogar tiene una enfermedad grave, PG&E debe dar 15 días adicionales de aviso — menciónelo cuando llame.' },
      { en: 'You may qualify for the Medical Baseline rate discount, which can lower your monthly bill permanently.', es: 'Puede calificar para el descuento Medical Baseline, que puede reducir su factura mensual permanentemente.' },
      { en: 'Emergency energy assistance funds may be available through 211.org — call 2-1-1 to check.', es: 'Fondos de asistencia energética de emergencia pueden estar disponibles en 211.org — llame al 2-1-1 para verificar.' },
    ],
    keyInfo: [
      { en: 'Account number: 7654-321-0',   es: 'Número de cuenta: 7654-321-0' },
      { en: 'Amount due: $342.00',          es: 'Monto pendiente: $342.00' },
      { en: 'Due date: May 14, 2026',       es: 'Fecha límite: 14 de mayo de 2026' },
      { en: 'PG&E: 1-800-743-5000',         es: 'PG&E: 1-800-743-5000' },
    ],
  },
  {
    id: 2,
    category: 'medical',
    icon: 'health_and_safety',
    title:       { en: 'Medicaid Renewal',         es: 'Medicaid' },
    issuer:      'Dept. of Health Services',
    urgency:     'act-now',
    deadlineLabel: { en: 'Respond this week',      es: 'Responder esta semana' },
    daysLeft:    14,
    receivedDate:{ en: 'May 9, 2026',        es: '9 de mayo de 2026' },
    done: false,
    summary: {
      en: 'Your Medicaid health coverage will end May 25 unless you renew it. This affects all doctor visits, prescriptions, and emergency care for everyone on your plan.',
      es: 'Su cobertura de salud Medicaid terminará el 25 de mayo si no la renueva. Esto afecta todas las visitas al médico, medicamentos y urgencias para todos en su plan.',
    },
    steps: [
      {
        id: 1, done: false,
        title:  { en: 'Call to renew by phone',    es: 'Llame para renovar por teléfono' },
        detail: { en: 'Have your ID and Social Security number ready. The call takes about 15 minutes.', es: 'Tenga su identificación y número de Seguro Social listo. La llamada dura unos 15 minutos.' },
        phone: '1-800-541-2831',
      },
      {
        id: 2, done: false,
        title:  { en: 'Or renew online',           es: 'O renueve en línea' },
        detail: { en: 'Go to coveredca.com. Create an account if you don\'t have one — your information may already be pre-filled.', es: 'Vaya a coveredca.com. Cree una cuenta si no tiene — su información puede estar pre-cargada.' },
        phone: null,
      },
      {
        id: 3, done: false,
        title:  { en: 'Tell them if your income changed', es: 'Informe si sus ingresos cambiaron' },
        detail: { en: 'If your income went up or down this year, mention it. You may qualify for a better plan or higher savings.', es: 'Si sus ingresos subieron o bajaron este año, menciónelo. Puede calificar para un plan mejor o más ahorros.' },
        phone: null,
      },
    ],
    hiddenPaths: [
      { en: 'Even if you miss this deadline, you have 90 days to appeal and request reinstatement. Ask for a "fair hearing."', es: 'Incluso si pierde esta fecha, tiene 90 días para apelar y pedir la reinstalación. Pida una "audiencia imparcial."' },
      { en: 'If your income is zero or you\'re between jobs, you still qualify — don\'t assume you don\'t.', es: 'Si su ingreso es cero o está entre empleos, aún califica — no asuma que no.' },
    ],
    keyInfo: [
      { en: 'Deadline: May 25, 2026',       es: 'Fecha límite: 25 de mayo de 2026' },
      { en: 'Renewal line: 1-800-541-2831', es: 'Línea de renovación: 1-800-541-2831' },
      { en: 'Hours: Mon–Fri 8am–5pm',       es: 'Horario: Lun–Vie 8am–5pm' },
      { en: 'Online: coveredca.com',         es: 'En línea: coveredca.com' },
    ],
  },
  {
    id: 3,
    category: 'school',
    icon: 'school',
    title:       { en: 'School Enrollment Form',   es: 'Formulario de la escuela' },
    issuer:      'Jefferson Elementary School',
    urgency:     'act-soon',
    deadlineLabel: { en: 'Due June 30',            es: 'Vence el 30 de junio' },
    daysLeft:    47,
    receivedDate:{ en: 'May 10, 2026',       es: '10 de mayo de 2026' },
    done: false,
    summary: {
      en: 'Jefferson Elementary School needs you to re-enroll your child for next school year by June 30. Missing this date may mean losing their guaranteed spot.',
      es: 'La Escuela Primaria Jefferson necesita que vuelva a inscribir a su hijo para el próximo año escolar antes del 30 de junio. No cumplir esta fecha puede significar perder su lugar garantizado.',
    },
    steps: [
      {
        id: 1, done: false,
        title:  { en: 'Complete the 4-page enrollment packet', es: 'Complete el paquete de inscripción de 4 páginas' },
        detail: { en: 'Includes: health form, emergency contacts, photo release, and free lunch application.', es: 'Incluye: formulario de salud, contactos de emergencia, autorización de fotos y solicitud de almuerzo gratis.' },
        phone: null,
      },
      {
        id: 2, done: false,
        title:  { en: 'Return packet to school office', es: 'Entregue el paquete en la oficina' },
        detail: { en: 'Drop off at 1450 Lincoln Ave (Mon–Fri 8am–3pm) or submit online at jeffersonelem.edu.', es: 'Entregue en 1450 Lincoln Ave (lun–vie 8am–3pm) o envíe en línea a jeffersonelem.edu.' },
        phone: null,
      },
      {
        id: 3, done: false,
        title:  { en: 'Apply for free or reduced lunch', es: 'Solicite almuerzo gratis o reducido' },
        detail: { en: 'The form is in the packet. You may qualify based on your household income — apply at the same time.', es: 'El formulario está en el paquete. Puede calificar según el ingreso del hogar — solicite al mismo tiempo.' },
        phone: null,
      },
    ],
    hiddenPaths: [
      { en: 'If your family is experiencing homelessness or living in temporary housing, your child has the right to enroll immediately — no permanent address required. Ask about the McKinney-Vento Act.', es: 'Si su familia está sin hogar o en vivienda temporal, su hijo tiene derecho a inscribirse de inmediato — no se requiere dirección permanente. Pregunte sobre la Ley McKinney-Vento.' },
      { en: 'If your child has an IEP or special needs, bring a copy when you enroll to ensure services continue from day one.', es: 'Si su hijo tiene un IEP o necesidades especiales, traiga una copia al inscribirse para garantizar que los servicios continúen desde el primer día.' },
    ],
    keyInfo: [
      { en: 'Deadline: June 30, 2026',      es: 'Fecha límite: 30 de junio de 2026' },
      { en: 'Address: 1450 Lincoln Ave',    es: 'Dirección: 1450 Lincoln Ave' },
      { en: 'Hours: Mon–Fri 8am–3pm',       es: 'Horario: Lun–Vie 8am–3pm' },
      { en: 'Online: jeffersonelem.edu',     es: 'En línea: jeffersonelem.edu' },
    ],
  },
]

export const SCAN_RESULT_DOC = {
  id: 4,
  category: 'legal',
  icon: 'gavel',
  title:       { en: '3-Day Eviction Notice',      es: 'Aviso de desalojo — 3 días' },
  issuer:      'Property Management',
  urgency:     'act-now',
  deadlineLabel: { en: 'Action before May 14',     es: 'Acción antes del 14 mayo' },
  daysLeft:    3,
  receivedDate:{ en: 'May 11, 2026',       es: '11 de mayo de 2026' },
  done: false,
  summary: {
    en: 'Your landlord is formally demanding you pay $1,850 in unpaid rent within 3 days — or vacate the apartment. This is the legal first step of an eviction. You have more rights than this letter suggests.',
    es: 'Su arrendador exige formalmente que pague $1,850 de renta atrasada en 3 días — o desocupe el apartamento. Este es el primer paso legal de un desalojo. Usted tiene más derechos de los que esta carta sugiere.',
  },
  steps: [
    {
      id: 1, done: false,
      title:  { en: 'Call a free legal aid hotline now', es: 'Llame ahora a una línea de ayuda legal gratuita' },
      detail: { en: 'They help tenants facing eviction at no cost. Ask for emergency assistance.', es: 'Ayudan a inquilinos en riesgo de desalojo sin costo. Pida asistencia de emergencia.' },
      phone: '415-982-1300',
    },
    {
      id: 2, done: false,
      title:  { en: 'Do NOT move out yet',          es: 'NO se mude todavía' },
      detail: { en: 'A 3-day notice is not a court order. You have legal rights and more time than this letter suggests.', es: 'Un aviso de 3 días no es una orden judicial. Tiene derechos legales y más tiempo del que esta carta sugiere.' },
      phone: null,
    },
    {
      id: 3, done: false,
      title:  { en: 'Apply for emergency rental assistance', es: 'Solicite asistencia de renta de emergencia' },
      detail: { en: 'Funds may be available to cover what you owe and stop the eviction entirely.', es: 'Puede haber fondos disponibles para cubrir lo que debe y detener el desalojo por completo.' },
      phone: '2-1-1',
    },
  ],
  hiddenPaths: [
    { en: 'Even after a court eviction is filed, you can stop the entire process by paying rent in full before the court date.', es: 'Incluso después de que se presente un caso de desalojo en el tribunal, puede detener todo el proceso pagando la renta completa antes de la fecha del juicio.' },
    { en: 'You have the right to a court trial — do not skip the court date if it is scheduled. Not showing up means you automatically lose.', es: 'Tiene derecho a un juicio — no falte a la fecha del tribunal si está programada. No presentarse significa perder automáticamente.' },
    { en: 'In many cities, landlords cannot evict without "just cause." Ask the legal aid hotline if this applies to your city.', es: 'En muchas ciudades, los arrendadores no pueden desalojar sin "causa justificada." Pregunte a la línea de ayuda legal si esto aplica a su ciudad.' },
  ],
  keyInfo: [
    { en: 'Amount demanded: $1,850.00',    es: 'Monto exigido: $1,850.00' },
    { en: 'Response deadline: 3 days',     es: 'Plazo de respuesta: 3 días' },
    { en: 'Bay Area Legal Aid: 415-982-1300', es: 'Bay Area Legal Aid: 415-982-1300' },
    { en: 'Emergency rental help: 2-1-1',  es: 'Ayuda de renta de emergencia: 2-1-1' },
  ],
}
