/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Atkinson Hyperlegible Next"', '"Atkinson Hyperlegible"', 'system-ui', 'sans-serif'],
      },
      colors: {
        'primary':                    '#0c5252',
        'on-primary':                 '#ffffff',
        'primary-container':          '#2d6a6a',
        'on-primary-container':       '#abe8e7',
        'primary-fixed':              '#b1eeed',
        'primary-fixed-dim':          '#95d1d1',
        'on-primary-fixed':           '#002020',
        'on-primary-fixed-variant':   '#074f4f',
        'secondary':                  '#805600',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#fdc265',
        'on-secondary-container':     '#754e00',
        'secondary-fixed':            '#ffddb0',
        'secondary-fixed-dim':        '#f7bc60',
        'on-secondary-fixed':         '#281800',
        'on-secondary-fixed-variant': '#614000',
        'tertiary':                   '#4b4946',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#63615d',
        'on-tertiary-container':      '#e1dcd8',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'background':                 '#fbf9f8',
        'on-background':              '#1b1c1c',
        'surface':                    '#fbf9f8',
        'on-surface':                 '#1b1c1c',
        'surface-variant':            '#dae5e4',
        'on-surface-variant':         '#3f4948',
        'outline':                    '#6f7979',
        'outline-variant':            '#bec8c8',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f5f3f2',
        'surface-container':          '#efeded',
        'surface-container-high':     '#e9e7e7',
        'surface-container-highest':  '#e4e2e1',
        'inverse-surface':            '#303030',
        'inverse-on-surface':         '#f2f0ef',
        'inverse-primary':            '#95d1d1',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg:   '0.75rem',
        xl:   '1rem',
        '2xl':'1.25rem',
        '3xl':'1.5rem',
        full: '9999px',
      },
      animation: {
        'fade-up':     'fadeUp 0.35s ease-out both',
        'fade-in':     'fadeIn 0.25s ease-out both',
        'scan-line':   'scanLine 2s ease-in-out infinite',
        'spin-slow':   'spin 1.2s linear infinite',
        'pulse-ring':  'pulseRing 1.5s ease-out infinite',
        'bounce-dot1': 'bounceDot 1s 0.0s ease-in-out infinite',
        'bounce-dot2': 'bounceDot 1s 0.15s ease-in-out infinite',
        'bounce-dot3': 'bounceDot 1s 0.3s ease-in-out infinite',
      },
      keyframes: {
        fadeUp: {
          '0%':   { opacity: 0, transform: 'translateY(14px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%':   { opacity: 0 },
          '100%': { opacity: 1 },
        },
        scanLine: {
          '0%, 100%': { transform: 'translateY(-10px)', opacity: 0.5 },
          '50%':      { transform: 'translateY(10px)',  opacity: 1 },
        },
        pulseRing: {
          '0%':   { transform: 'scale(1)',   opacity: 0.6 },
          '100%': { transform: 'scale(1.8)', opacity: 0   },
        },
        bounceDot: {
          '0%, 80%, 100%': { transform: 'translateY(0)'   },
          '40%':           { transform: 'translateY(-8px)' },
        },
      },
    },
  },
  plugins: [],
}
